### ISSUE TITLE
Update question

### ISSUE THREAD

**Issue by shadeimi** [spotify/python-graphwalker#5]
Hi all, 
This package is aligned with the latest graphwalker package (3.3.0 at the moment)? if not, what's missing?

Thank you

**Comment by aes** [comment]
It's missing a few things, primarily the guards, because they make it very
hard to reason about the model. It also has a quite different idea of
subgraphs: In the original Java version, they're more like function calls,
in the Python version, they're joined in, using the same vertices for
references to the same name. There's probably more, but the short version
is that it doesn't have the ambition of being an identical
re-implementation.

cheers
aes
